# Generated by Django 4.2 on 2023-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Пользователь', 'Пользователь'), ('Сотрудник', 'Сотрудник')], default='Пользователь', max_length=50, verbose_name='Статус пользователя'),
        ),
    ]
